### ISSUE TITLE
Ask: Revert back from obfuscation state(with modified data) to original state without obfuscation (with new/modified data)

### ISSUE THREAD

**Issue by brm-ryd** [josacar/triki#18]
Hi Sorry, to asking this through here,

do you think there's a way to revert the dump data back to original (non obfuscation variables) with some new data after there are some new / modified data in obfuscation state db ? 

Thank you

**Comment by josacar** [comment]
the process just generates a masked dump, you can choose to mask data via random, hashed ( cannot get original, i.e. SHA-512 ) or kinda encrypted ( can get original, i.e. AES ).

The import process just drops tables to start from a pristine state.
