### ISSUE TITLE
Whitelist all tables by default

### ISSUE THREAD

**Issue by isaiev** [josacar/triki#7]
Hi.

I have a case where I want to keep all columns from all tables except table "X".
Not it is possible to generate a scaffold, but this solution requires changing the configuration every time some table is added or deleted.
If all tables and all columns will be kept, then I'll have the opportunity to build a static binary of `obfuscator` and forget about it for a long time.

**Comment by josacar** [comment]
This feature was not in the radar for me, current behavior forces obfuscator to be in sync with production data, so you will avoid storing PII/PHI/PCI data outside of production. PR are welcome to add a option flag.
